[package]
name = "model"
version = "0.1.0"
edition = "2021"
rust-version = "1.81.0"

[features]
train = [ "burn/train" ]

[dependencies]
burn = { workspace = true, features = [ "dataset", "vision" ] }
